---
name: CustomCapes
api:
- 3.0.0
version: 2.0.5-beta
author: StrafelessPvP, ElektroPrinz
main: CustomCapes\Skin
website: https://github.com/StrafelessPvP
commands:
  changeskin:
    permission: skinchanger.cmd.changeskin
    description: "L\xE4sst dich deinen Skin im Spiel wechseln"
    usage: /changeskin [SkinName] <Spieler>
  changecape:
    permission: skinchanger.cmd.changecape
    description: "L\xE4sst dich deinen Umhang im Spiel wechseln"
    usage: /changecape [UmhangName] <Spieler>
  skins:
    permission: skinchanger.cmd.skins
    description: Zeigt dir die Standard Skins des Servers an
    usage: /skins
    default: true
permissions:
  skinchanger:
    children:
      skinchanger.bypass:
        description: This will let you bypass the skin changing on join if it is enabled
      skinchanger.cmd:
        children:
          skinchanger.cmd.changeskin:
            default: op
          skinchanger.cmd.changecape:
            default: op
          skinchanger.cmd.skins:
            default: op
...
